### ISSUE TITLE
Zoom to Size, resulting in error

### ISSUE THREAD

**Issue by matthewflinchbaugh** [meerk40t/meerk40t#149] opened 2020-02-22 20:30 UTC
View menu option Zoom to Size is crashing on 0.5.1, and a few of the previous versions.
![image](https://user-images.githubusercontent.com/3926459/75098760-2a312b00-5588-11ea-8cec-a37021e9ee71.png)

**Comment by tatarize** [comment] 2020-02-22 21:39
This bug was caused by me forgetting that was a button and not pressing it. The bbox() thing doesn't need the argument I gave it since it was the only thing that function really worked on. But, never checked.

0.5.2 has this corrected in the current commit.

https://github.com/meerk40t/meerk40t/commit/e4bef48e8d80b1415c3ca006f547bc1eea824f6a

**Comment by tatarize** [comment] 2020-03-11 12:45
This is fixed with 0.5.2 going live.

**Closed by tatarize** 2020-03-11 12:45 UTC
Labels: bug, closeable issue
