### ISSUE TITLE
[Bug]: Fillets are lost in DXF files 

### ISSUE THREAD

**Issue by jpagliaccio** [meerk40t/meerk40t#2275] opened 2023-11-20 12:04 UTC
### Summary Description

Fillets are lost when opening DXF files created by LibreCAD. Tried DXF formats 2007 thru R12 with the same result. 

### Additional Details

The same file will open properly in Inkscape but there is an import note about extrusions when opening DXF with fillets. LibreCAD 2.2.0.2 and Meerk40t v0.9.3000.  Bevels open properly.  

### MeerK40t Version

v0.9.3000

### MeerK40t Type

Executable

### Your Operating System

Linux

**Comment by jpirnay** [comment] 2023-11-20 14:50
Not sure I follow - trying it with a simple rectangle myself, here's what mk imported:
![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/fed0f1e8-71b4-4fdf-aa76-eb90ed6150da)
Can you share the culprit file, please?

**Comment by Sophist-UK** [comment] 2023-11-20 17:09
No attachment because you sent it as an email reply rather than using a browser to attach it. And since a picture is worth a thousand words, some pictures of the DXF in the originating program and when it is loaded into Meerk40t would help.

**Comment by tatarize** [comment] 2023-11-21 01:51
Yeah, I might need the minimum example of this, since DXF allows so many ways to make arcs.

**Comment by jpagliaccio** [comment] 2023-11-21 11:52
Tatarize,

In LibreCAD 2.2.02
1) File, New
2) Line, 2 Points
3) Draw some lines making corners
(tip: right click for a recently used menu)

[image: image.png]
4) Tools, Modify, Fillet
5) Enter Radius, (eg: 20)
[image: image.png]
6) Select the first line (towards the corner)
7) Select the second line (towards the corner)

[image: image.png]
8) Save
Open the file in meerk40t

PS: I tried the Freehand tool to draw arcs and those don't work either.

Regards,
Joe

**Comment by Sophist-UK** [comment] 2023-11-21 12:02
@jpagliaccio I repeat - PLEASE use a web browser on this page to comment on this issue so that your attachments get added!!

**Comment by jpirnay** [comment] 2023-11-21 12:13
Created in LibreCad 2.2
![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/b536bd5b-fc00-4deb-aa0f-179a3d7077ba)


Meerk40t after file load
![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/263ca161-b265-446e-8bb2-2234d7085bcb)

**Comment by jpagliaccio** [comment] 2023-11-21 12:23
LibreCAD 
1) 2 Lines
![image](https://github.com/meerk40t/meerk40t/assets/7680161/888acd3b-4287-45d3-beca-c367c7bde558)
2) Fillet 
![image](https://github.com/meerk40t/meerk40t/assets/7680161/d551e85c-dd4e-4eb7-874a-3d98dac2d679)
3) Meerkt40 
![image](https://github.com/meerk40t/meerk40t/assets/7680161/1614e3a7-83b4-48d9-ad85-ce79f5a27e4a)

**Comment by jpirnay** [comment] 2023-11-21 12:27
Can you please confirm your version? This bug was fixed with the full 0.9.3 version - https://github.com/meerk40t/meerk40t/releases/tag/0.9.3001

**Comment by jpagliaccio** [comment] 2023-11-22 13:15
MeerK40t v0.9.3001
Python 3.6.8
wxPython 4.1.1 gtk3 (phoenix) wxWidgets 3.1.5
The pre-compiled MeerK40t-Linux version from https://github.com/meerk40t/meerk40t/releases
I just did a fresh download and tested. Same result (no fillets).

**Comment by jpirnay** [comment] 2023-11-22 15:44
Again, my tests are not able to reproduce this, so I would need an example file that demonstrates the issue, please.

**Comment by Sophist-UK** [comment] 2023-11-22 16:08
Jens, if @jpagliaccio doesn't upload his example file so that you can reproduce this issue, I think you might have to closed it as unreproducible.

**Comment by tatarize** [comment] 2023-11-22 16:39
We need an example. You could email me at tatarize at gmail if you want, or actually drop it to the issue. We don't have a copy of this, but it's entirely possible that it's using an unsupported dxf thing to do the fillets and we just need to extend the support but we'd need an example to check that.

**Comment by jpagliaccio** [comment] 2023-11-23 13:33
Emailed the file.

**Comment by tatarize** [comment] 2023-11-24 20:38
Nothing received...Checked spam etc.

**Comment by jpirnay** [comment] 2023-11-25 16:39
Hmm, I need to flip it, but then I have:
![grafik](https://github.com/meerk40t/meerk40t/assets/2670784/c47b0e7b-0128-4bf8-9357-ec65bd16f7fb)

**Comment by jpirnay** [comment] 2023-11-25 17:14
So according to the latest code:
- [x] fillets work as they should
- [ ] text is placed correctly

So, a different bug...

**Comment by jpirnay** [comment] 2023-11-25 20:03
The text issue (plus some issues around correct image import) will be dealt with under  PR#2302

**Closed** 2024-01-15 00:03 UTC
Labels: Type: Bug, Status: Completed
