### ISSUE TITLE
[0.8.1] Duplicate entries in Spool history 

### ISSUE THREAD

**Issue by Sophist-UK** [meerk40t/meerk40t#1524] opened 2022-11-28 16:13 UTC
1 job (which BTW didn't raster when it should have), 4 entries....

![image](https://user-images.githubusercontent.com/3001893/204326855-7f55bad4-7740-4160-b849-7e207eb66e09.png)

**Comment by jpirnay** [comment] 2022-11-29 10:28
Logic added to prevent duplicate entries, although not sure from where it came from. So more a bandaid than a patch.

**Comment by Sophist-UK** [comment] 2022-12-03 16:40
If it is any help I noticed that entries are added if I close and open the spooler window.

**Comment by tatarize** [comment] 2022-12-04 02:39
The issue is that on a window load when it registers the signal, in this case, `"spooler;completed"` it force resends the last valid signal. This is so that if you have some text boxes that are filled and updated with signals, you don't need the signal to fire after the window loads. The signals always save the last signal and when registered it "sends" the last detected signal so that that box will always have the last valid information.

The problem here is that the spooler history is actually using signals to send the information and the spooler window is doing the logging. So each time you re-open the window, you actually get that last signal again, which saves but could have already been added to the logs.

```python
    @signal_listener("spooler;completed")
    def on_spooler_completed(self, origin, info, *args):
        # Info is just a tuple with the label and the runtime
        # print ("Signalled...", type(origin).__name__, type(info).__name__)
        if info is None:
            return
        if len(info) > 1 and info[1] is None:
            return
        self.refresh_history(newestinfo=info)
        self.save_history()
```

#1540 should also be helpful in correcting this, while it doesn't do this work yet, since it's touching on code jpirnay authored almost exclusively, the spoolers should be able to log their own information about what they did and use a signal to notify any windows which may be open (but do not need to be open) that the recorded history has changed. This is also intended to allow additional information like original time estimate to be saved to the log without needing to display in the spooler, etc. So if we have potentially useful information, we can record that information without needing to use it. Also, we could hide entries in the log rather than needing to clear the entire set of logs, since that gets a lot easier when we're just passing info to and from a consistent source.

**Comment by tatarize** [comment] 2023-03-13 00:09
This was changed and fully corrected fixed with the update to the logging for the jobs.

**Closed by tatarize** 2023-03-13 00:09 UTC
Labels: Status: Completed, Context: Logging
