### ISSUE TITLE
Manual needed for Meerk40t

### ISSUE THREAD

**Issue by pkarza** [meerk40t/meerk40t#207] opened 2020-08-23 15:26 UTC
Just a note - the learning curve is fairly steep:
I have watched nearly all videos on Youtube - and when adding a graphic, for example, I can dither, step and scale, etc - it used to be that you could add a 'hull' (I believe) but this is no longer in existence...  you can etch the graphic, but can't cut it out.

Another example is ppi - I understand the concept that you use a percentage or number over 1000 - example 500/1000 would give you half  of the pulses per inch - but what should the output of your K40 be set to  - 100%, for example - or set to about 80% and then use that as the ceiling?

These are two examples (and there are others) that I and others would like to know the answers for and not only would I like to know them, I would suggest that a WIKI manual be created where users could add to it - to help in the creation of a use manual like K40 Whisperer.  Because of not knowing how to cut a picture, I had to resort to Whisperer to perform this job.

Thanks for the great work, and I look forward to helping in any way I can.

**Comment by joerlane** [comment] 2020-08-23 18:50
Can't speak about the hull issue.

I can tell you that I set my K40 power to be what I need for the job. For example; if I have a job that requires cutting; I set my hardware power to be just enough to perform the cutting I want at 1,000 PPI. I have a volt meter on my power control knob so I can reproduce that power settings to the 100th of a volt. For my last job I have a note in the file that says 0.88v setting; which is about 4mA on the laser power meter. Most jobs I run between 4-6mA on the power meter (but that's just me). Then I adjust things like engraving and raster/image jobs to fit that power level. Typically that means setting engraving down to 200-300 PPI range because the gantry can't draw complex shapes at high speed - mine run around 16mm/s which is safe enough for tiny vector details. Then I increase the raster speed to hit the depth I want at 1,000 PPI by adjusting the speed and steps (my most recent job was 200mm/s and raster step 2). 

On the other hand Tatarize will likely mirror what you said; set hardware power to a reasonable value (~80%), and use PPI for control. Which works better for you? Which works better for the job or material at hand?

In terms of a picture; it should be the "same" as whisperer. Load the picture, and cut it. You can leave it at 1,000 PPI for simple jobs. Then you only have to worry about the speed of the raster, and hardware power setting based on the material you intend to use. Whisperer setup is exactly the same, set speed, and set hardware power... If you want to make the job run faster, you can mess with the Raster Steps too; which will change the vertical stepping and speed up the job if you don't need such high density of laser for the particular material. 

One thing that might not be mentioned anywhere. If you load an image directly into MeerK40t; it will place that image top left in the bed. Depending on if you shift home position or not; that might be way too close to the left edge since raster jobs need overscan to slow down and speed up the head. Default is 20 mil; but I typically run about 60 mil overscan. That means you'll need that much extra space on the left and right side to avoid crashing the head into the side walls. 

I'm sure @tatarize will stop in and comment sometime soon as well. Hope this is at least somewhat helpful to your questions. And don't worry. I've occasionally had to step back to Whisperer for a job. It does help out a lot to identify those issues though, so things can be made more clear; and/or MeerK40t can be improved as needed.

**Comment by pkarza** [comment] 2020-08-23 23:30
Good points

Like you  I have a voltmeter that gives precise voltage and a multitude pot
(10x) and I usually do a test fire to adjust the ma by the analog meter..

5v seems to be 20ma and 1v is about 4 ma etc.

I like to load the image directly but although I can dither step and scale
there is no way to cut around the border.  That would be a great addition.

I have been playing with ppi and am rastering at 200/1000 and set the speed
at 100-200 mms/second and have noticed some buffering issues with larger
burns.

**Comment by tatarize** [comment] 2020-08-24 05:59
https://www.youtube.com/watch?v=lh2IT0CMqUY

This should explain the meaning of the PPI and why PWM has a duty cycle that is expressed in percent. 

I did remove the convex hull feature. It was a bit weird. If you want to cut an image out. You can put that image in a cut operation and it'll cut it out.  The convex hull was cryptic and really intended to let you check the positioning for the object. There's now a button that does that much less cryptically and strangely in navigation.  It was a weird and poorly implemented feature. When I did that more properly it got removed.

There is the cut use case. I could definitely see needing to generate a rectangle from an image rather than cut the image edges in an undocumented "drag it into a cut operation" feature. I'll be adding a couple tools to just let you draw a rectangle in a few versions or so.

**Comment by pkarza** [comment] 2020-08-25 04:06
I am looking to the drag into cut feature...

As for putting the image into a cut operation - how?

**Comment by joerlane** [comment] 2020-08-25 04:10
Drag the image in question from Elements in the tree, into a cut operation. If you don't already have a cut operation; you can right click Operations, and then Add Operation. Then double click on that and set it to cut.

**Comment by joerlane** [comment] 2020-08-25 04:13
I also did this yesterday from the MeerK40t Terminal because I wanted a 3mm border. I selected the image, and then used the coordinates and size numbers; then added my padding when using the rect command in the CLI (rect xStart, yStart, xWidth, yWidth). I still ended up tweaking placement in the GUI, and had to add it to a Cut operation from Elements since it is black stroke color by default.

**Comment by tatarize** [comment] 2020-08-25 05:39
You can also do `stroke red` it's usually red for cuts. And when you reclassify everything it'll usually end up right.

https://www.youtube.com/watch?v=VupbPMkZzGw

He's not wrong though, that is harder than it needs to be.

**Comment by tatarize** [comment] 2020-12-18 13:16
Images for a would-be manual.

![wxmeerk40t](https://user-images.githubusercontent.com/3302478/102618581-e9466c00-40ef-11eb-90d3-cd60a4b25970.png)
![wxmeerk40t-2](https://user-images.githubusercontent.com/3302478/102618567-e21f5e00-40ef-11eb-9e28-d7bcd7f97656.png)
![Navigation](https://user-images.githubusercontent.com/3302478/102618586-eb102f80-40ef-11eb-9e64-a052fadaa66a.png)
![Usblog](https://user-images.githubusercontent.com/3302478/102618589-ec415c80-40ef-11eb-81af-a4748cb0ad1a.png)
![spooler](https://user-images.githubusercontent.com/3302478/102618592-ee0b2000-40ef-11eb-90ae-81324953f506.png)
![Controller](https://user-images.githubusercontent.com/3302478/102618599-f06d7a00-40ef-11eb-8408-e56898ce3385.png)
![Preferences](https://user-images.githubusercontent.com/3302478/102618603-f19ea700-40ef-11eb-8003-455b0eb569db.png)
![Devices](https://user-images.githubusercontent.com/3302478/102618612-f5cac480-40ef-11eb-8541-992453de0baa.png)
![Camera](https://user-images.githubusercontent.com/3302478/102618615-f7948800-40ef-11eb-950b-3ae6689bd383.png)
![Keymap](https://user-images.githubusercontent.com/3302478/102618620-f95e4b80-40ef-11eb-8924-bd9592d0e3dd.png)
![Notes](https://user-images.githubusercontent.com/3302478/102618625-fbc0a580-40ef-11eb-8808-262d0acf20fc.png)
![RotarySettings](https://user-images.githubusercontent.com/3302478/102618632-fe22ff80-40ef-11eb-9320-aa2ca316a8b7.png)
![About](https://user-images.githubusercontent.com/3302478/102618638-ffecc300-40ef-11eb-865d-beaa503d304d.png)
![Adjustments](https://user-images.githubusercontent.com/3302478/102618641-01b68680-40f0-11eb-86cc-619e4550313f.png)
![OperationProperties](https://user-images.githubusercontent.com/3302478/102618646-02e7b380-40f0-11eb-9398-361620c41db4.png)
![PathProperties](https://user-images.githubusercontent.com/3302478/102618649-0418e080-40f0-11eb-9d5a-1e6dabe976b3.png)
![ImageProperties](https://user-images.githubusercontent.com/3302478/102618652-05e2a400-40f0-11eb-9739-ce122b9016eb.png)
![TextProperties](https://user-images.githubusercontent.com/3302478/102618656-0713d100-40f0-11eb-9dad-e3a4cf9a846c.png)

**Comment by tatarize** [comment] 2020-12-18 13:20
![Job](https://user-images.githubusercontent.com/3302478/102619045-b2bd2100-40f0-11eb-8afe-2dcb2081f52f.png)

**Comment by tatarize** [comment] 2020-12-18 13:28
![RasterWizard](https://user-images.githubusercontent.com/3302478/102619740-c61cbc00-40f1-11eb-9f7a-fd99e263d091.png)
![Settings](https://user-images.githubusercontent.com/3302478/102619747-c7e67f80-40f1-11eb-95f9-9a1ac155abcb.png)

**Comment by tatarize** [comment] 2020-12-19 14:34
![Alignment](https://user-images.githubusercontent.com/3302478/102691817-3136c300-41c4-11eb-9eb7-a5d0861f7912.png)

**Comment by Sophist-UK** [comment] 2021-05-19 23:40
I am currently working on restructuring the Wiki with the idea of making it the comprehensive source of documentation.

Essentially a few high level classes of Wiki page:
* Beginner - how to get started
* Doc - the comprehensive manual
* Help - ad-hoc user help for things not directly MeerK40t (like how best to use Inkscape to prepare your SVG)
* Install - detailed install instructions for various types of install
* Tech - detailed ad-hoc tech stuff braindump area mainly for developers

Any help with this gratefully received as there is way to much for me to do by myself.

**Comment by tatarize** [comment] 2021-08-12 22:38
Sophist's work here is good enough to close the issue. More documentation is always useful. But, this actually exists now.

**Closed by tatarize** 2021-08-12 22:38 UTC
Labels: Type: Documentation, Status: In Progress

**Comment by Sophist-UK** [comment] 2021-08-13 09:11
There may be a basic structure for the Wiki, but it is still only (maybe) 5% complete.

I write wiki pages as I get time, but that is infrequent. **WE NEED HELP WITH THE WIKI** - it is too big a job for one or two people.

That said, having an Issue open will not make any difference.
