### ISSUE TITLE
problem with Splines in DFX

### ISSUE THREAD

**Issue by gyan007** [meerk40t/meerk40t#314] opened 2021-01-23 06:41 UTC
the splines are not showing correctly in v.0.6.16

[problem_with_splines_in_DFX.zip](https://github.com/meerk40t/meerk40t/files/5859804/problem_with_splines_in_DFX.zip)

**Comment by tatarize** [comment] 2021-01-23 06:56
![visicut](https://user-images.githubusercontent.com/3302478/105571486-fa912280-5d04-11eb-93f4-6ac938c29589.png)
![meerk40t](https://user-images.githubusercontent.com/3302478/105571487-fb29b900-5d04-11eb-9829-2f845cb4905b.png)


Visicut rotates it and moves it to the bed. But, clearly should be hourglass shaped. It is not.

**Comment by tatarize** [comment] 2021-01-23 07:00
The issue is in ezdxf. I used their code for splines which works great except for rational b-splines which these are, so it used the fallback of using lines.

**Comment by tatarize** [comment] 2021-01-23 07:09
Actually there maybe another approximation method to use first before resorting to this terrible one.

**Comment by tatarize** [comment] 2021-01-23 07:27
Okay, splines will now have 2 fallbacks but, that's fine. Corrected it. But, we finished 0.6.16 and then proceeded to break 0.6.17 instantly with a big can of worms. So lemme go ahead and maybe shove those back in the bottle. I wouldn't go clicking any spinners in GTK based windowing systems, and closing the window that's in the beta... 

Assuming you're a windows user. Would kinda need to know the build to give you with the fix.

**Comment by joerlane** [comment] 2021-01-23 07:38
What operating system are you using MeerK40t v0.6.16 on?

**Comment by gyan007** [comment] 2021-01-23 07:41
I am using windows 10 64-bit and windows8.1 32-bit

**Comment by tatarize** [comment] 2021-01-23 07:43
Okay, I'll have a beta out for you in a minute or two.

**Comment by tatarize** [comment] 2021-01-23 07:46
https://github.com/meerk40t/meerk40t/releases/tag/0.6.17-beta1

**Comment by tatarize** [comment] 2021-01-23 07:47
![meerk40t-beta](https://user-images.githubusercontent.com/3302478/105572477-3a0f3d00-5d0c-11eb-82ac-073e407665c1.png)

**Comment by gyan007** [comment] 2021-01-23 07:48
Cool, Thanks!

**Comment by gyan007** [comment] 2021-01-23 08:04
![image](https://user-images.githubusercontent.com/2134623/105572822-982a3780-5d81-11eb-9eac-fa4f67d608a5.jpeg)

It corrected the Big spline but turned small line segments into wave like patterns

**Comment by tatarize** [comment] 2021-01-23 08:10
Hm. Might be the guess it's taking. Really those are also going to be splines but weighted differently and it's taking a solid guess at where they should be.

**Comment by tatarize** [comment] 2021-01-23 08:15
Apparently yeah, higher numbers for better approximations. 5 seems about right for that.

Making a new beta.

**Comment by tatarize** [comment] 2021-01-23 08:17
https://github.com/meerk40t/meerk40t/releases/tag/0.6.17-beta2

**Comment by tatarize** [comment] 2021-01-23 08:19
![beta2](https://user-images.githubusercontent.com/3302478/105573170-8197c800-5d10-11eb-98c4-3739f86d165d.png)

I could go higher but the gains seem to be less above this. You could also slightly tweak it to use lines in that part of the path if you're messing with the original dxf. Seems to have a solid approximation vs. cost value.

**Comment by gyan007** [comment] 2021-01-23 08:24
ya, looks good. Using lines for straight paths instead of all splines in dfx would solve the problem for me at least

**Comment by tatarize** [comment] 2021-01-23 08:27
Especially when you're weighting them to make them straight there. It's gotta convert them to beziers so there's a bit of wiggle in the approximation. But, that's solid enough for everything there. At least it's a lot closer and much less noticeable.

**Comment by gyan007** [comment] 2021-01-23 08:31
I  tried importing dxf to Inkscape ->> to svg --> to meerk40 and it came out fine.

**Comment by tatarize** [comment] 2021-01-23 08:33
Inkscape probably has better math for the b-splines. It's likely a better fallback for that. I'm just working with ezdxf. Which is why at first this was marked blocked. Because I didn't think it was doable. But, there's a better fallback there, but certainly isn't perfect. There's likely better algorithms. Especially since you're really making lines there.

**Comment by gyan007** [comment] 2021-01-23 08:35
yeah, Thanks!

**Comment by tatarize** [comment] 2021-01-23 08:36
Also, 5 might be too high, I'm seeing some performance issues. So yeah, either don't really use those or run it through ezdxf. I'll take it under advisement though those approximations are approximate.

**Comment by tatarize** [comment] 2021-01-23 08:37
Oh, nm. I temporarily put that to 10 to see how good it got. Yeah, that's a performance drain.

**Closed** 2021-01-30 21:45 UTC
Labels: Context: DXF, Priority: Low, Status: In Progress, Type: Bug, Work: Obvious
