### ISSUE TITLE
Failed Install on Mac

### ISSUE THREAD

**Issue by stan916** [meerk40t/meerk40t#248] opened 2020-10-19 09:26 UTC
I have installed Meerk40t on my Mac (running Catalina 10.15.6) using the latest version 0.6.7 and the program will not run correctly. I can't open any files and the bed grid is missing from the display. Also the grey area around the bid seems smaller than on my Windows install.

![74D22E09-2C97-4B86-899F-E89993996698](https://user-images.githubusercontent.com/54368953/96426677-76a33800-11f5-11eb-9306-984c160d471c.png)

When I try to open a file nothing happens but I can't then close down Meerk40t as it just hangs so I have to force quit. All the dialogue boxes for settings, controller, etc seem to work ok. I have not tried to connect it to my K40 yet.

**Comment by joerlane** [comment] 2020-10-19 09:49
Could be helpful to see if anything changes on the screen when trying to load an SVG file, or an image. Also; I'm somewhat concerned about the double title bar on the main MeerK40t window. Never seen that before, and it may be indicative of something else messing with the UI in a strange way. Does the white box zoom in an out, draw selection boxes, or scroll around; or is it frozen?

Working to get a similar version of OS X installed and configured to test this myself. In the short term, you could try to create a new user on your computer; and run MeerK40t from that new account. Might be surprised...

**Comment by stan916** [comment] 2020-10-19 09:52
Nothing happens when trying to load a file. The left hand column of
operations, etc, is selectable and the dialogues associated all work
correctly. The white box also does nothing.

Will give it a go with a new user.

**Comment by stan916** [comment] 2020-10-19 09:54
UPDATE! I have just installed 0.6.5 and this seems to work! I'm doing this
remotely to my Mac at home from work so I'm a bit limited with what I want
to do, but so far a file has opened correctly at least and the grid is
there, etc, etc, so it looks good so far.

**Comment by tatarize** [comment] 2020-10-19 09:57
That means whatever the issue is, it's actually going to somewhat minor.

**Comment by stan916** [comment] 2020-10-19 10:04
I can now open a file but there is something weird going on with the naming
of the engrave paths, see attached screenshot.

**Comment by joerlane** [comment] 2020-10-19 10:07
Ok. That's good news. I don't think I've made any changes at all on the Mac build system since MeerK40t version 0.6.5.
There aren't a lot of major changes to MeerK40t since 0.6.5 either; so it should work alright for you in the short term. I'll certainly be looking in to this; interested to see what 0.6.7 does with a clean install of OS X 10.15.6. I can always compile on that OS if it's absolutely necessary.

**Comment by joerlane** [comment] 2020-10-19 10:10
> I can now open a file but there is something weird going on with the naming of the engrave paths, see attached screenshot.

Screenshot didn't attach for some reason. The path descriptions had some long names in older versions (like 0.6.5) describing the SVG path. There should be a tiny icon to the left showing it if it's not terribly large. You can also click on the path in the tree, and arrow up and down to see which ones they are in the scene.

**Comment by stan916** [comment] 2020-10-19 10:11
Thx. I’ll try 0.6.6 as well just out of curiosity.

**Comment by stan916** [comment] 2020-10-19 10:17
0.6.6 no good, just a blank screen where the bed and grid should be,
screenshot Capture2. Sorry forgot to attach the previous one for 0.6.5, now
attached also

**Comment by tatarize** [comment] 2020-10-19 10:18
I don't see a screenshot. Might not attach from an email response or something.

**Comment by stan916** [comment] 2020-10-19 10:21
![Capture2](https://user-images.githubusercontent.com/54368953/96433700-2b8d2300-11fd-11eb-878d-80e16cd12c11.PNG)
![Capture](https://user-images.githubusercontent.com/54368953/96433714-2c25b980-11fd-11eb-81d1-dd520a9bb78f.PNG)

**Comment by stan916** [comment] 2020-10-19 10:21
I was using gmail to reply, just attached them on github.

**Comment by stan916** [comment] 2020-10-20 08:22
Further update. The 0.6.5 install on the Mac runs fine except for the element naming shown in the screenshot. However there is another issue which affects BOTH Windows and MacOS. No matter what buffer size limiting figure is used the laser pauses briefly for a couple of seconds every now and then (maybe every 45 secs - 1 minute) during a raster if the PPI is set at anything less than 1000 (i.e. full power). 
I can't be 100% certain but it looks like the rastering intensity between each pause changes slightly as there are visible changes in the rastering on the job which seem to coincide with when the pauses occur, but I need to do some more tests on that tonight to be 100% sure.

**Comment by tatarize** [comment] 2020-10-20 08:43
The element naming was one of the minor things changed. People insisting that the gibberishy names weren't helpful so they were changed.

**Comment by tatarize** [comment] 2020-10-20 08:52
@stan916 will have information on stuttering and why it happens.
https://www.youtube.com/watch?v=blhbbq22sGU

Since this is a issues forum there's a couple things being tried to get around this. In the plot planning I'm adding an option to do grouping where the actual pulse train will be moved by 1 pixel here and there to make sure it doesn't stutter. As well as some dot length patterning which may certainly help. The video explains why it happens, and I can likely do some stuff like remove a double check for OK issue that may actually crank out a few extra ms timewise.

**Comment by joerlane** [comment] 2020-10-21 04:49
Initial issue was verified to be a problem on another 10.15.6 Mac. On launch it shows a light grey background in the large pane of the main window. Resizing the window draws the dark grey background and main drawing scene in white. The rulers and reticle never show up, even after "refresh" command in the MeerK40t Terminal.

Loading a file does not update the tree or main window. Unsure if starting a job will queue anything after loading the file. Or issuing the refresh command again and again.

After loading a file; clicking the Start Job button would bring up the Jobs window, and it would be known if the file loaded if those components were in the queue.

**Comment by joerlane** [comment] 2020-10-24 07:41
The recently uploaded 0.6.8 release is built using a different version of wxPython. This needs to be tested on OS X 10.15.6 and similar.

**Comment by tatarize** [comment] 2020-10-26 06:02
Might have fixed some internal -psn_?_???? crash thing. @stan916 can you confirm 0.6.9 works for you?

**Comment by joerlane** [comment] 2020-10-28 09:32
The MeerK40t 0.6.9 updates has been confirmed to work on a Mac running OS X 10.5.7. 

There is some reason to suspect that the previously non-functional versions (0.6.6-0.6.8) may function if launched from the command line as well as either a file to open, or the -v switch. Some testing indicated that process may actual fix the app so that double clicking works afterward. Not terribly important information now that MeerK40t 0.6.9 is available...

**Comment by joerlane** [comment] 2020-11-02 17:53
MeerK40t 0.6.10 was released. Still awaiting user verification to close this issue. Versions 0.6.10, and 0.6.9 should both work in Mac OS X 10.15.x.

**Comment by stan916** [comment] 2020-12-16 09:17
All fixed on 0.6.10

**Closed** 2020-12-16 09:17 UTC
Labels: OSX, compile, invalid
